coursefinder/coursefinder/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('coursefinderapp.urls')),
    path('admin/', admin.site.urls),
]

coursefinder/coursefinderapp/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

coursefinder/coursefinderapp/models.py
from django.db import models


COUNTRY_CHOICES = (
    ('XF', 'England'),
    ('XG', 'Northern Ireland'),
    ('XH', 'Scotland'),
    ('XI', 'Wales'),
)


class Location(models.Model):

    locid = models.CharField(max_length=2)
    ukprn = models.CharField(max_length=8)
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=2, choices=COUNTRY_CHOICES, default='XK')
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        unique_together = ('locid', 'ukprn')


class Job(models.Model):
    description = models.CharField(max_length=100)

    def __str__(self):
        return "%s" % self.description


class Course(models.Model):

    MODE_CHOICES = (
        ('1', 'Full-time'),
        ('2', 'Part-time'),
        ('3', 'Both'),
    )

    DISTANCE_CHOICES = (
        ('0', 'Course is available other than by distance learning'),
        ('1', 'Course is only available through distance learning'),
        ('2', 'Course is optionally available through distance learning'),
    )

    pubukprn = models.CharField(max_length=25)
    ukprn = models.CharField(max_length=25)
    kiscourseid = models.CharField(max_length=25)
    title = models.CharField(max_length=100)
    url = models.URLField(max_length=100)
    mode = models.CharField(max_length=1, choices=MODE_CHOICES, default='1')
    distance = models.CharField(max_length=1, choices=DISTANCE_CHOICES, default='0')
    aim = models.CharField(max_length=10)

    location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True, blank=True)

    jobs = models.ManyToManyField(Job)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        unique_together = ('pubukprn', 'ukprn', 'kiscourseid', 'mode')

coursefinder/coursefinderapp/forms.py
from django import forms

from .models import Job, COUNTRY_CHOICES


class FilterForm(forms.Form):
    industries = forms.ModelMultipleChoiceField(
        queryset=Job.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    countries = forms.MultipleChoiceField(
        choices=COUNTRY_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    limit = forms.IntegerField(
        min_value=1,
        max_value=1000,
        initial=100,
        required=False,
    )

coursefinder/coursefinderapp/views.py
from django.shortcuts import render

from .forms import FilterForm
from .models import Course


def index(request):

    courses = []

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = FilterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data

            filters = {}

            selected_countries = data['countries']
            if len(selected_countries) > 0:
                filters['location__country__in'] = selected_countries

            selected_jobs = data['industries']
            if len(selected_jobs) > 0:
                filters['jobs__in'] = selected_jobs

            if len(filters) > 0:
                limit = data['limit']
                courses = Course.objects.filter(**filters).order_by('title')[:limit]

    # if a GET (or any other method) we'll create a blank form
    else:
        form = FilterForm()

    return render(request, 'index.html', {'form': form, 'courses': courses})

coursefinder/templates/coursefinderapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Course Finder{% endblock %}</title>
</head>

<style>

#wrapper {
}

#sidebar {
 display: inline-block;
 float: left;
 box-sizing: border-box;
 border-style: solid;
 border-width: 1px;
 margin-left: 10px;
 margin-right: 10px;
 padding: 1em 1em 1em 1em;
}

#content {
 overflow: auto;
}

#courseList {
 width: 75%;
 padding-left: 2em;
}

.course {
 box-sizing: border-box;
 border-style: solid;
 border-width: 1px;
 padding-bottom: 1em;
 padding-left: 1em;
 margin-bottom: 1em;
}

</style>


<body>

<div id="wrapper">
    <div id="sidebar">
        {% block sidebar %}
            {% include "coursefinderapp/filter_form.html" %}
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}
            {% include "coursefinderapp/course_list.html" %}
        {% endblock %}
    </div>
</div>


</body>
</html>

coursefinder/templates/coursefinderapp/course.html
<div class="course">
    <h3>{{ course.title }}</h3>

    <table style="width:90%; table-layout: fixed;">
        <tr>
            <td style="width: 30%;">{{ course.aim }}</td>
            <td style="width: 70%;">{{ course.location.name }}, {{ course.location.get_country_display }}</td>
        </tr>
        <tr>
            <td style="width: 30%;">Mode: {{ course.get_mode_display }}</td>
            <td style="width: 70%;">{{ course.get_distance_display }}</td>
        </tr>
        <tr>
            <td><a href="{{ course.url }}">Go to page</a></td>
        </tr>
    </table>
</div>

coursefinder/templates/coursefinderapp/course_list.html
<div id="courseList">

    <h1>Course List:</h1>

    {% if courses %}

    <ul style="list-style-type: none; padding-left: 0;">
        {% for course in courses %}
            <li>
                {% include "coursefinderapp/course.html" %}
            </li>
        {% endfor %}
    </ul>

    {% else %}

    <h3>No course to show</h3>

    {% endif %}
</div>

coursefinder/templates/coursefinderapp/filter_form.html
<form action="/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Filter" style="font-size:20px; width: 5em; float: right"/>
</form>

coursefinder/templates/index.html
{% extends "coursefinderapp/base.html" %}